# Generated by Django 2.2 on 2019-04-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190419_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='udpated_at',
            new_name='updated_at',
        ),
    ]
