# Generated by Django 2.2 on 2019-06-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='embedded',
            field=models.TextField(blank=True, verbose_name='Vídeo Embutido(embedded)'),
        ),
    ]
