# Generated by Django 2.2 on 2019-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
