# Generated by Django 2.2 on 2019-05-05 17:20

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Nome de usuario invalido, só pode conter @/./+/-/', 'invalid')], verbose_name='Nome de Usuário'),
        ),
    ]
